import json

# רשימה מלאה ומעודכנת של כל המניות — נאסד"ק 100, S&P 500, ת"א 125
names = {

    # ══════════════════════════════════════════════════
    # נאסד"ק 100 — רשימה רשמית מעודכנת יוני 2026
    # ══════════════════════════════════════════════════
    "nvda":"NVDA","nvidia":"NVDA","נווידיה":"NVDA","אינבידיה":"NVDA","אנווידיה":"NVDA",
    "goog":"GOOG","googl":"GOOGL","google":"GOOGL","גוגל":"GOOGL","alphabet":"GOOGL","אלפבית":"GOOGL",
    "aapl":"AAPL","apple":"AAPL","אפל":"AAPL",
    "msft":"MSFT","microsoft":"MSFT","מייקרוסופט":"MSFT","מיקרוסופט":"MSFT",
    "amzn":"AMZN","amazon":"AMZN","אמזון":"AMZN",
    "avgo":"AVGO","broadcom":"AVGO","ברודקום":"AVGO",
    "tsla":"TSLA","tesla":"TSLA","טסלה":"TSLA",
    "meta":"META","facebook":"META","פייסבוק":"META","מטא":"META",
    "mu":"MU","micron":"MU","מיקרון":"MU",
    "wmt":"WMT","walmart":"WMT","וולמארט":"WMT",
    "amd":"AMD","advanced micro devices":"AMD","אי אם די":"AMD",
    "asml":"ASML","אסמל":"ASML",
    "intc":"INTC","intel":"INTC","אינטל":"INTC",
    "csco":"CSCO","cisco":"CSCO","סיסקו":"CSCO",
    "cost":"COST","costco":"COST","קוסטקו":"COST",
    "lrcx":"LRCX","lam research":"LRCX","לאם ריסרץ'":"LRCX",
    "arm":"ARM","ארם":"ARM",
    "pltr":"PLTR","palantir":"PLTR","פלנטיר":"PLTR",
    "amat":"AMAT","applied materials":"AMAT","אפלייד מטריאלס":"AMAT",
    "nflx":"NFLX","netflix":"NFLX","נטפליקס":"NFLX",
    "txn":"TXN","texas instruments":"TXN","טקסס אינסטרומנטס":"TXN",
    "qcom":"QCOM","qualcomm":"QCOM","קוואלקום":"QCOM",
    "klac":"KLAC","kla":"KLAC","קיי אל איי":"KLAC",
    "lin":"LIN","linde":"LIN","לינדה":"LIN",
    "panw":"PANW","palo alto":"PANW","פאלו אלטו":"PANW","palo alto networks":"PANW",
    "adi":"ADI","analog devices":"ADI","אנלוג דיווייסס":"ADI",
    "stx":"STX","seagate":"STX","סיגייט":"STX",
    "tmus":"TMUS","t-mobile":"TMUS","טי מובייל":"TMUS",
    "pep":"PEP","pepsi":"PEP","pepsico":"PEP","פפסי":"PEP",
    "app":"APP","applovin":"APP","אפליוין":"APP",
    "wdc":"WDC","western digital":"WDC","ווסטרן דיגיטל":"WDC",
    "amgn":"AMGN","amgen":"AMGN","אמג'ן":"AMGN",
    "crwd":"CRWD","crowdstrike":"CRWD","קראודסטרייק":"CRWD",
    "mrvl":"MRVL","marvell":"MRVL","מרוול":"MRVL",
    "gild":"GILD","gilead":"GILD","גילאד":"GILD",
    "isrg":"ISRG","intuitive surgical":"ISRG","אינטואיטיב סורג'יקל":"ISRG",
    "shop":"SHOP","shopify":"SHOP","שופיפיי":"SHOP",
    "hon":"HON","honeywell":"HON","האניוול":"HON",
    "bkng":"BKNG","booking":"BKNG","בוקינג":"BKNG",
    "pdd":"PDD","temu":"PDD","טמו":"PDD","פיידידי":"PDD",
    "sbux":"SBUX","starbucks":"SBUX","סטארבקס":"SBUX",
    "vrtx":"VRTX","vertex":"VRTX","ורטקס":"VRTX",
    "ceg":"CEG","constellation energy":"CEG","קונסטליישן":"CEG",
    "cdns":"CDNS","cadence":"CDNS","קדנס":"CDNS",
    "mar":"MAR","marriott":"MAR","מריוט":"MAR",
    "adbe":"ADBE","adobe":"ADBE","אדובי":"ADBE",
    "ftnt":"FTNT","fortinet":"FTNT","פורטינט":"FTNT",
    "snps":"SNPS","synopsys":"SNPS","סינופסיס":"SNPS",
    "cmcsa":"CMCSA","comcast":"CMCSA","קומקאסט":"CMCSA",
    "adp":"ADP","automatic data processing":"ADP","איי די פי":"ADP",
    "intu":"INTU","intuit":"INTU","אינטואיט":"INTU",
    "meli":"MELI","mercado libre":"MELI","מרקדו ליברה":"MELI",
    "mnst":"MNST","monster":"MNST","מונסטר":"MNST",
    "csx":"CSX","csx corporation":"CSX","סי אס אקס":"CSX",
    "nxpi":"NXPI","nxp":"NXPI","אן אקס פי":"NXPI",
    "ddog":"DDOG","datadog":"DDOG","דאטאדוג":"DDOG",
    "mpwr":"MPWR","monolithic power":"MPWR","מונוליתיק":"MPWR",
    "abnb":"ABNB","airbnb":"ABNB","אירביאנבי":"ABNB",
    "mdlz":"MDLZ","mondelez":"MDLZ","מונדלז":"MDLZ",
    "rost":"ROST","ross stores":"ROST","רוס":"ROST",
    "orly":"ORLY","o'reilly":"ORLY","אוריילי":"ORLY",
    "dash":"DASH","doordash":"DASH","דורדאש":"DASH",
    "aep":"AEP","american electric power":"AEP","אמריקן אלקטריק":"AEP",
    "ctas":"CTAS","cintas":"CTAS","סינטס":"CTAS",
    "wbd":"WBD","warner bros":"WBD","וורנר ברוס":"WBD","warner bros discovery":"WBD",
    "bkr":"BKR","baker hughes":"BKR","בייקר יוז":"BKR",
    "regn":"REGN","regeneron":"REGN","ריג'נרון":"REGN",
    "pcar":"PCAR","paccar":"PCAR","פאקאר":"PCAR",
    "fang":"FANG","diamondback":"FANG","דיאמונדבק":"FANG",
    "mstr":"MSTR","microstrategy":"MSTR","strategy":"MSTR","מיקרוסטרטג'י":"MSTR",
    "mchp":"MCHP","microchip":"MCHP","מיקרוצ'יפ":"MCHP",
    "fast":"FAST","fastenal":"FAST","פאסטנל":"FAST",
    "ea":"EA","electronic arts":"EA","אלקטרוניק ארטס":"EA",
    "xel":"XEL","xcel energy":"XEL","אקסל אנרגי":"XEL",
    "fer":"FER","ferrovial":"FER","פרוביאל":"FER",
    "odfl":"ODFL","old dominion":"ODFL","אולד דומיניון":"ODFL",
    "exc":"EXC","exelon":"EXC","אקסלון":"EXC",
    "adsk":"ADSK","autodesk":"ADSK","אוטודסק":"ADSK",
    "idxx":"IDXX","idexx":"IDXX","איידקס":"IDXX",
    "ttwo":"TTWO","take-two":"TTWO","take two":"TTWO","טייק טו":"TTWO",
    "ccep":"CCEP","coca-cola europacific":"CCEP","קוקה קולה אירופה":"CCEP",
    "kdp":"KDP","keurig dr pepper":"KDP","קיוריג":"KDP",
    "alny":"ALNY","alnylam":"ALNY","אלנילם":"ALNY",
    "pypl":"PYPL","paypal":"PYPL","פייפאל":"PYPL",
    "tri":"TRI","thomson reuters":"TRI","תומסון רויטרס":"TRI",
    "payx":"PAYX","paychex":"PAYX","פייצ'קס":"PAYX",
    "axon":"AXON","axon enterprise":"AXON","טייזר":"AXON",
    "wday":"WDAY","workday":"WDAY","וורקדיי":"WDAY",
    "rop":"ROP","roper":"ROP","רופר":"ROP",
    "cprt":"CPRT","copart":"CPRT","קופארט":"CPRT",
    "khc":"KHC","kraft heinz":"KHC","קראפט היינץ":"KHC",
    "gehc":"GEHC","ge healthcare":"GEHC","ג'י אי הלת'קר":"GEHC",
    "dxcm":"DXCM","dexcom":"DXCM","דקסקום":"DXCM",
    "ctsh":"CTSH","cognizant":"CTSH","קוגניזנט":"CTSH",
    "team":"TEAM","atlassian":"TEAM","אטלסיאן":"TEAM",
    "insm":"INSM","insmed":"INSM","אינסמד":"INSM",
    "vrsk":"VRSK","verisk":"VRSK","ורסיק":"VRSK",
    "zs":"ZS","zscaler":"ZS","זסקיילר":"ZS",
    "chtr":"CHTR","charter":"CHTR","צ'רטר":"CHTR",
    "csgp":"CSGP","costar":"CSGP","קוסטאר":"CSGP",
    "spcx":"SPCX","spacex":"SPCX","ספייסקס":"SPCX","ספייס אקס":"SPCX","חלל":"SPCX",

    # ══════════════════════════════════════════════════
    # S&P 500 — מניות נוספות שאינן בנאסד"ק 100
    # ══════════════════════════════════════════════════
    "jpm":"JPM","jpmorgan":"JPM","jp morgan":"JPM","ג'יפי מורגן":"JPM",
    "bac":"BAC","bank of america":"BAC","בנק אמריקה":"BAC",
    "wfc":"WFC","wells fargo":"WFC","וולס פארגו":"WFC",
    "gs":"GS","goldman sachs":"GS","גולדמן סאקס":"GS","גולדמן":"GS",
    "ms":"MS","morgan stanley":"MS","מורגן סטנלי":"MS",
    "v":"V","visa":"V","ויזה":"V",
    "ma":"MA","mastercard":"MA","מאסטרקארד":"MA",
    "brk-b":"BRK-B","berkshire":"BRK-B","ברקשייר":"BRK-B","באפט":"BRK-B",
    "axp":"AXP","american express":"AXP","אמריקן אקספרס":"AXP",
    "c":"C","citigroup":"C","סיטיגרופ":"C","סיטי":"C",
    "blk":"BLK","blackrock":"BLK","בלאקרוק":"BLK",
    "schw":"SCHW","schwab":"SCHW","שוואב":"SCHW",
    "usb":"USB","us bancorp":"USB","יו אס בנקורפ":"USB",
    "pnc":"PNC","pnc financial":"PNC","פי אן סי":"PNC",
    "cof":"COF","capital one":"COF","קפיטל וואן":"COF",
    "spgi":"SPGI","s&p global":"SPGI","אס אנד פי גלובל":"SPGI",
    "mco":"MCO","moody's":"MCO","מודיס":"MCO",
    "lly":"LLY","eli lilly":"LLY","lilly":"LLY","אלי לילי":"LLY",
    "jnj":"JNJ","johnson":"JNJ","ג'ונסון":"JNJ","johnson and johnson":"JNJ",
    "unh":"UNH","unitedhealth":"UNH","יונייטד הלת'":"UNH",
    "abbv":"ABBV","abbvie":"ABBV","אבווי":"ABBV",
    "pfe":"PFE","pfizer":"PFE","פייזר":"PFE",
    "mrk":"MRK","merck":"MRK","מרק":"MRK",
    "bmy":"BMY","bristol myers":"BMY","בריסטול מאיירס":"BMY",
    "cvs":"CVS","cvs health":"CVS","סי וי אס":"CVS",
    "ci":"CI","cigna":"CI","סיגנה":"CI",
    "hum":"HUM","humana":"HUM","יומנה":"HUM",
    "elv":"ELV","elevance":"ELV","אלוונס":"ELV",
    "hca":"HCA","hca healthcare":"HCA","אייץ' סי איי":"HCA",
    "tmo":"TMO","thermo fisher":"TMO","תרמו פישר":"TMO",
    "dhr":"DHR","danaher":"DHR","דנהר":"DHR",
    "abt":"ABT","abbott":"ABT","אבוט":"ABT",
    "syk":"SYK","stryker":"SYK","סטרייקר":"SYK",
    "bsx":"BSX","boston scientific":"BSX","בוסטון סיינטיפיק":"BSX",
    "mdt":"MDT","medtronic":"MDT","מדטרוניק":"MDT",
    "xom":"XOM","exxon":"XOM","אקסון":"XOM","exxon mobil":"XOM",
    "cvx":"CVX","chevron":"CVX","שברון":"CVX",
    "cop":"COP","conocophillips":"COP","קונוקו פיליפס":"COP",
    "slb":"SLB","schlumberger":"SLB","שלמברגר":"SLB",
    "hal":"HAL","halliburton":"HAL","הליברטון":"HAL",
    "oxy":"OXY","occidental":"OXY","אוקסידנטל":"OXY",
    "eog":"EOG","eog resources":"EOG","איי או ג'י":"EOG",
    "psx":"PSX","phillips 66":"PSX","פיליפס 66":"PSX",
    "vlo":"VLO","valero":"VLO","ולרו":"VLO",
    "ge":"GE","general electric":"GE","ג'נרל אלקטריק":"GE",
    "cat":"CAT","caterpillar":"CAT","קטרפילר":"CAT",
    "ba":"BA","boeing":"BA","בואינג":"BA",
    "rtx":"RTX","raytheon":"RTX","רייתיאון":"RTX",
    "lmt":"LMT","lockheed":"LMT","לוקהיד":"LMT","lockheed martin":"LMT",
    "noc":"NOC","northrop":"NOC","נורת'רופ גרומן":"NOC",
    "gd":"GD","general dynamics":"GD","ג'נרל דיינמיקס":"GD",
    "mmm":"MMM","3m":"MMM","תלת אם":"MMM",
    "emr":"EMR","emerson":"EMR","אמרסון":"EMR",
    "etn":"ETN","eaton":"ETN","איטון":"ETN",
    "de":"DE","deere":"DE","ג'ון דיר":"DE","john deere":"DE",
    "unp":"UNP","union pacific":"UNP","יוניון פסיפיק":"UNP",
    "ups":"UPS","united parcel":"UPS","יו פי אס":"UPS",
    "hd":"HD","home depot":"HD","הום דיפו":"HD",
    "low":"LOW","lowe's":"LOW","לואוס":"LOW",
    "tgt":"TGT","target":"TGT","טארגט":"TGT",
    "mcd":"MCD","mcdonald's":"MCD","מקדונלדס":"MCD",
    "nke":"NKE","nike":"NKE","נייקי":"NKE",
    "tjx":"TJX","tjx companies":"TJX","טי ג'י אקס":"TJX",
    "ko":"KO","coca cola":"KO","קוקה קולה":"KO","coke":"KO",
    "pg":"PG","procter gamble":"PG","פרוקטר וגמבל":"PG",
    "pm":"PM","philip morris":"PM","פיליפ מוריס":"PM",
    "mo":"MO","altria":"MO","אלטריה":"MO",
    "dis":"DIS","disney":"DIS","דיסני":"DIS",
    "orcl":"ORCL","oracle":"ORCL","אורקל":"ORCL",
    "crm":"CRM","salesforce":"CRM","סיילספורס":"CRM",
    "ibm":"IBM","איי בי אם":"IBM",
    "now":"NOW","servicenow":"NOW","סרביס נאו":"NOW",
    "acn":"ACN","accenture":"ACN","אקסנצ'ר":"ACN",
    "anet":"ANET","arista":"ANET","אריסטה":"ANET",
    "dell":"DELL","dell technologies":"DELL","דל":"DELL",
    "bx":"BX","blackstone":"BX","בלאקסטון":"BX",
    "kkr":"KKR","kkr & co":"KKR","קיי קיי ארקיי":"KKR",
    "cb":"CB","chubb":"CB","צ'אב":"CB",
    "pgr":"PGR","progressive":"PGR","פרוגרסיב":"PGR",
    "trv":"TRV","travelers":"TRV","טרוולרס":"TRV",
    "all":"ALL","allstate":"ALL","אולסטייט":"ALL",
    "met":"MET","metlife":"MET","מטלייף":"MET",
    "pru":"PRU","prudential":"PRU","פרודנשל":"PRU",
    "afl":"AFL","aflac":"AFL","אפלאק":"AFL",
    "nee":"NEE","nextera":"NEE","נקסט אירה":"NEE",
    "duk":"DUK","duke energy":"DUK","דיוק אנרגי":"DUK",
    "so":"SO","southern company":"SO","סאת'רן":"SO",
    "d":"D","dominion":"D","דומיניון":"D",
    "sre":"SRE","sempra":"SRE","סמפרה":"SRE",
    "amt":"AMT","american tower":"AMT","אמריקן טאואר":"AMT",
    "pld":"PLD","prologis":"PLD","פרולוג'יס":"PLD",
    "cci":"CCI","crown castle":"CCI","קראון קאסל":"CCI",
    "eqix":"EQIX","equinix":"EQIX","אקווינקס":"EQIX",
    "psa":"PSA","public storage":"PSA","פאבליק סטורג'":"PSA",
    "well":"WELL","welltower":"WELL","וולטאואר":"WELL",
    "vrt":"VRT","vertiv":"VRT","ורטיב":"VRT",
    "pwr":"PWR","quanta services":"PWR","קוואנטה":"PWR",
    "nem":"NEM","newmont":"NEM","ניומונט":"NEM","זהב":"NEM",
    "fcx":"FCX","freeport":"FCX","פריפורט":"FCX","נחושת":"FCX",
    "apd":"APD","air products":"APD","אייר פרודקטס":"APD",
    "ecl":"ECL","ecolab":"ECL","אקולב":"ECL",
    "shw":"SHW","sherwin williams":"SHW","שרווין וויליאמס":"SHW",
    "mck":"MCK","mckesson":"MCK","מקסון":"MCK",
    "cah":"CAH","cardinal health":"CAH","קרדינל הלת'":"CAH",
    "uber":"UBER","אובר":"UBER",
    "lyft":"LYFT","ליפט":"LYFT",
    "coin":"COIN","coinbase":"COIN","קוינבייס":"COIN",
    "snow":"SNOW","snowflake":"SNOW","סנואופלייק":"SNOW",
    "mdb":"MDB","mongodb":"MDB","מונגו דיבי":"MDB",
    "net":"NET","cloudflare":"NET","קלאודפלייר":"NET",
    "okta":"OKTA","אוקטה":"OKTA",
    "zm":"ZM","zoom":"ZM","זום":"ZM",
    "gev":"GEV","ge vernova":"GEV","ג'י אי ורנובה":"GEV",
    "tt":"TT","trane":"TT","טריין":"TT",
    "jci":"JCI","johnson controls":"JCI","ג'ונסון קונטרולס":"JCI",
    "wmb":"WMB","williams":"WMB","וויליאמס":"WMB",
    "wm":"WM","waste management":"WM","פסולת":"WM",
    "nsc":"NSC","norfolk southern":"NSC","נורפולק":"NSC",
    "zts":"ZTS","zoetis":"ZTS","זואטיס":"ZTS",
    "aon":"AON","אאון":"AON",
    "mmc":"MMC","marsh":"MMC","מארש":"MMC",
    "dks":"DKS","dick's sporting":"DKS","דיקס":"DKS",
    "cmg":"CMG","chipotle":"CMG","צ'יפוטלה":"CMG",
    "yum":"YUM","yum brands":"YUM","יאם":"YUM",
    "dri":"DRI","darden":"DRI","דארדן":"DRI",
    "hlt":"HLT","hilton":"HLT","הילטון":"HLT",
    "azn":"AZN","astrazeneca":"AZN","אסטרה זנקה":"AZN",
    "nvo":"NVO","novo nordisk":"NVO","נובו נורדיסק":"NVO","אוזמפיק":"NVO",
    "gsk":"GSK","glaxo":"GSK","גלאקסו":"GSK",
    "sny":"SNY","sanofi":"SNY","סנופי":"SNY",
    "biib":"BIIB","biogen":"BIIB","ביוג'ן":"BIIB",
    "ilmn":"ILMN","illumina":"ILMN","אילומינה":"ILMN",
    "bntx":"BNTX","biontech":"BNTX","ביואנטק":"BNTX",
    "mrna":"MRNA","moderna":"MRNA","מודרנה":"MRNA",
    "wat":"WAT","waters":"WAT","ווטרס":"WAT",
    "a":"A","agilent":"A","אג'ילנט":"A",
    "ntra":"NTRA","natera":"NTRA","נטרה":"NTRA",
    "vrtx2":"VRTX","vertex2":"VRTX",
    "spgi2":"SPGI",
    "rga":"RGA","reinsurance group":"RGA","ריאינשורנס":"RGA",

    # ══════════════════════════════════════════════════
    # ת"א 125 — כל המניות
    # ══════════════════════════════════════════════════
    "teva":"TEVA.TA","טבע":"TEVA.TA","תבע":"TEVA.TA","teva pharmaceuticals":"TEVA.TA",
    "nice":"NICE.TA","נייס":"NICE.TA","nice systems":"NICE.TA",
    "chkp":"CHKP.TA","checkpoint":"CHKP.TA","צ'ק פוינט":"CHKP.TA","check point":"CHKP.TA",
    "mndy":"MNDY.TA","monday":"MNDY.TA","מאנדיי":"MNDY.TA","monday.com":"MNDY.TA",
    "wix":"WIX.TA","וויקס":"WIX.TA","ויקס":"WIX.TA",
    "glbe":"GLBE.TA","global-e":"GLBE.TA","גלובל-e":"GLBE.TA","גלובל אי":"GLBE.TA",
    "icl":"ICL.TA","כיל":"ICL.TA","israel chemicals":"ICL.TA","כימיקלים לישראל":"ICL.TA",
    "eslt":"ESLT.TA","אלביט":"ESLT.TA","elbit":"ESLT.TA","elbit systems":"ESLT.TA","אלביט מערכות":"ESLT.TA",
    "amot":"AMOT.TA","עמות":"AMOT.TA","amot investments":"AMOT.TA",
    "mgdl":"MGDL.TA","מגדל":"MGDL.TA","migdal":"MGDL.TA","מגדל ביטוח":"MGDL.TA",
    "harl":"HARL.TA","הראל":"HARL.TA","harel":"HARL.TA","הראל ביטוח":"HARL.TA",
    "phoe":"PHOE.TA","פניקס":"PHOE.TA","phoenix":"PHOE.TA","הפניקס":"PHOE.TA",
    "dsct":"DSCT.TA","דיסקונט":"DSCT.TA","discount":"DSCT.TA","בנק דיסקונט":"DSCT.TA",
    "lumi":"LUMI.TA","לאומי":"LUMI.TA","leumi":"LUMI.TA","בנק לאומי":"LUMI.TA",
    "poli":"POLI.TA","פועלים":"POLI.TA","hapoalim":"POLI.TA","בנק הפועלים":"POLI.TA",
    "mzrh":"MZRH.TA","מזרחי":"MZRH.TA","mizrahi":"MZRH.TA","מזרחי טפחות":"MZRH.TA",
    "fibi":"FIBI.TA","הבינלאומי":"FIBI.TA","first international":"FIBI.TA","הבנק הבינלאומי":"FIBI.TA",
    "itrn":"ITRN.TA","אינטרן":"ITRN.TA","ituran":"ITRN.TA",
    "enlt":"ENLT.TA","אנלייט":"ENLT.TA","enlight":"ENLT.TA","אנלייט אנרגיה":"ENLT.TA",
    "spen":"SPEN.TA","שופרסל":"SPEN.TA","shufersal":"SPEN.TA",
    "camt":"CAMT.TA","קמטק":"CAMT.TA","camtek":"CAMT.TA",
    "crnt":"CRNT.TA","קרנט":"CRNT.TA","ceragon":"CRNT.TA",
    "nvmi":"NVMI.TA","נובה":"NVMI.TA","nova":"NVMI.TA","nova microelectronics":"NVMI.TA",
    "rdrd":"RDRD.TA","רד-רד":"RDRD.TA",
    "tsem":"TSEM.TA","טאוור":"TSEM.TA","tower":"TSEM.TA","tower semiconductor":"TSEM.TA","טאוור סמיקונדקטור":"TSEM.TA",
    "smdr":"SMDR.TA","סמדר":"SMDR.TA",
    "skbn":"SKBN.TA","סקייליין":"SKBN.TA",
    "prgo":"PRGO.TA","פרגו":"PRGO.TA","perrigo":"PRGO.TA",
    "gilt":"GILT.TA","גילת":"GILT.TA","gilat":"GILT.TA","גילת לוויין":"GILT.TA",
    "strs":"STRS.TA","סטרוס":"STRS.TA","strauss":"STRS.TA","סטרוס גרופ":"STRS.TA",
    "alhe":"ALHE.TA","אלה":"ALHE.TA",
    "azrg":"AZRG.TA","עזריאלי":"AZRG.TA","azrieli":"AZRG.TA","קבוצת עזריאלי":"AZRG.TA",
    "bway":"BWAY.TA","ביווי":"BWAY.TA",
    "dgns":"DGNS.TA","דיגנוסטיקס":"DGNS.TA",
    "dorl":"DORL.TA","דורל":"DORL.TA",
    "evgn":"EVGN.TA","אוורגרין":"EVGN.TA","evogene":"EVGN.TA",
    "ftal":"FTAL.TA","פטל":"FTAL.TA",
    "gish":"GISH.TA","גיש":"GISH.TA",
    "hdst":"HDST.TA","הדסת":"HDST.TA",
    "ilco":"ILCO.TA","ילקו":"ILCO.TA",
    "ilex":"ILEX.TA","אילקס":"ILEX.TA",
    "iscd":"ISCD.TA","ישרקארד":"ISCD.TA","isracard":"ISCD.TA",
    "kare":"KARE.TA","קארה":"KARE.TA",
    "krur":"KRUR.TA","קרור":"KRUR.TA",
    "lsco":"LSCO.TA","לסקו":"LSCO.TA",
    "mgor":"MGOR.TA","מגור":"MGOR.TA",
    "mish":"MISH.TA","מישלב":"MISH.TA",
    "mlsr":"MLSR.TA","מלסר":"MLSR.TA",
    "neto":"NETO.TA","נטו":"NETO.TA",
    "nfta":"NFTA.TA","נפטא":"NFTA.TA",
    "obas":"OBAS.TA","עובד באס":"OBAS.TA",
    "orad":"ORAD.TA","אוראד":"ORAD.TA",
    "plsn":"PLSN.TA","פלסן":"PLSN.TA",
    "ptbl":"PTBL.TA","פתאל":"PTBL.TA","fattal":"PTBL.TA","מלונות פתאל":"PTBL.TA",
    "rsel":"RSEL.TA","רסל":"RSEL.TA",
    "sano":"SANO.TA","סנו":"SANO.TA",
    "suur":"SUUR.TA","שור":"SUUR.TA",
    "tact":"TACT.TA","טאקט":"TACT.TA",
    "tdrn":"TDRN.TA","טדיראן":"TDRN.TA","tadiran":"TDRN.TA",
    "tlsy":"TLSY.TA","תלסי":"TLSY.TA",
    "tznr":"TZNR.TA","טצנר":"TZNR.TA",
    "ultr":"ULTR.TA","אולטרה":"ULTR.TA","ultra":"ULTR.TA",
    "unvo":"UNVO.TA","אונבו":"UNVO.TA",
    "vtna":"VTNA.TA","ויטנה":"VTNA.TA",
    "wlfl":"WLFL.TA","וולפסון":"WLFL.TA",
    "yaak":"YAAK.TA","יעקב":"YAAK.TA",
    "adgr":"ADGR.TA","אדגר":"ADGR.TA","adgar":"ADGR.TA",
    "allt":"ALLT.TA","אלוט":"ALLT.TA","allot":"ALLT.TA",
    "arad":"ARAD.TA","ארד":"ARAD.TA",
    "aryt":"ARYT.TA","אריית":"ARYT.TA",
    "asho":"ASHO.TA","אשוח":"ASHO.TA",
    "aviv":"AVIV.TA","אביב":"AVIV.TA",
    "bram":"BRAM.TA","ברם":"BRAM.TA",
    "bril":"BRIL.TA","ברילנס":"BRIL.TA",
    "clis":"CLIS.TA","קליס":"CLIS.TA",
    "difi":"DIFI.TA","דיפי":"DIFI.TA",
    "dnya":"DNYA.TA","דניה":"DNYA.TA","danya":"DNYA.TA","דניה סיבוס":"DNYA.TA",
    "elco":"ELCO.TA","אלקו":"ELCO.TA",
    "frog":"FROG.TA","פרוג":"FROG.TA","jfrog":"FROG.TA","ג'יפרוג":"FROG.TA",
    "gcmt":"GCMT.TA","גלובל קומוניטי":"GCMT.TA",
    "gdev":"GDEV.TA","ג'ידב":"GDEV.TA",
    "govn":"GOVN.TA","גובן":"GOVN.TA",
    "ifon":"IFON.TA","סלקום":"IFON.TA","cellcom":"IFON.TA",
    "igld":"IGLD.TA","אייגולד":"IGLD.TA",
    "inrm":"INRM.TA","אינרם":"INRM.TA",
    "isco":"ISCO.TA","איסקו":"ISCO.TA",
    "isop":"ISOP.TA","איסופארם":"ISOP.TA",
    "isra":"ISRA.TA","ישרא":"ISRA.TA",
    "jbnk":"JBNK.TA","ג'יבנק":"JBNK.TA","בנק ירושלים":"JBNK.TA",
    "kmda":"KMDA.TA","קמדה":"KMDA.TA","kamada":"KMDA.TA",
    "knfm":"KNFM.TA","קנפ מדיקל":"KNFM.TA",
    "mcrm":"MCRM.TA","מקרם":"MCRM.TA",
    "mgic":"MGIC.TA","מג'יק":"MGIC.TA","magic software":"MGIC.TA","מג'יק סופטוור":"MGIC.TA",
    "migi":"MIGI.TA","מיגי":"MIGI.TA",
    "mnin":"MNIN.TA","מינין":"MNIN.TA",
    "mran":"MRAN.TA","מראן":"MRAN.TA",
    "msbi":"MSBI.TA","מסבי":"MSBI.TA",
    "mtrx":"MTRX.TA","מטריקס":"MTRX.TA","matrix":"MTRX.TA",
    "mvne":"MVNE.TA","מבנה":"MVNE.TA",
    "mzor":"MZOR.TA","מזור":"MZOR.TA","mazor":"MZOR.TA",
    "nili":"NILI.TA","נילי":"NILI.TA",
}

with open("stock_names.json", "w", encoding="utf-8") as f:
    json.dump(names, f, ensure_ascii=False, indent=2)

print(f"✅ {len(names)} שמות נשמרו ל-stock_names.json!")
